@baseUrl=http://localhost:3000/api

@resourceName=categories


#@name getAll
GET {{baseUrl}}/{{resourceName}}

###

#@name postItem
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "name": "Bùi Quang Thắng"
}

###

#@name updateItem
PATCH {{baseUrl}}/{{resourceName}}/1
Content-Type: application/json

{
    "name": "Bùi Quang"
}

###

#@name deleteItem
DELETE  {{baseUrl}}/{{resourceName}}/2
